"""Setup script for VectorReVamp Enterprise Test Generation Platform"""

from setuptools import setup, find_packages
from pathlib import Path

# Read README
readme_file = Path(__file__).parent / "README.md"
long_description = readme_file.read_text() if readme_file.exists() else ""

setup(
    name="vectorrevamp",
    version="2.0.0",
    description="Enterprise AI-powered test generation platform with parallel processing, self-evolution, and strategic optimization",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="SWORDIntel",
    author_email="vectorrevamp@swordintelligence.airforce",
    url="https://github.com/SWORDIntel/VectorReVamp",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "psutil>=5.9.0",
        "networkx>=3.0",
        "pandas>=1.5.0",
        "scikit-learn>=1.3.0",
        "plotly>=5.0.0",
        "numpy>=1.24.0",
        "scipy>=1.11.0",
        "matplotlib>=3.7.0",
        "pytest>=7.0.0",
        "pytest-cov>=4.0.0",
        "coverage>=7.0.0",
    ],
    extras_require={
        "enterprise": [
            "dask>=2023.0.0",
            "ray>=2.0.0",
            "joblib>=1.3.0",
            "openai>=1.0.0",
            "anthropic>=0.5.0",
            "transformers>=4.30.0",
            "torch>=2.0.0",
            "chromadb>=0.4.0",
            "faiss-cpu>=1.7.0",
            "pluggy>=1.5.0",
            "cryptography>=41.0.0",
            "fastapi>=0.100.0",
            "pydantic>=2.0.0",
            "uvicorn>=0.23.0",
        ],
        "ai": [
            "openai>=1.0.0",
            "anthropic>=0.5.0",
            "transformers>=4.30.0",
            "torch>=2.0.0",
        ],
        "analytics": [
            "pandas>=1.5.0",
            "scikit-learn>=1.3.0",
            "plotly>=5.0.0",
            "numpy>=1.24.0",
            "scipy>=1.11.0",
            "matplotlib>=3.7.0",
            "seaborn>=0.12.0",
            "jupyter>=1.0.0",
        ],
        "plugins": [
            "pluggy>=1.5.0",
            "importlib-metadata>=6.0.0",
            "setuptools>=65.0.0",
        ],
        "security": [
            "cryptography>=41.0.0",
            "pyopenssl>=23.0.0",
            "bandit>=1.7.0",
            "safety>=2.3.0",
        ],
        "database": [
            "sqlalchemy>=2.0.0",
            "psycopg2-binary>=2.9.0",
            "pymongo>=4.0.0",
            "redis>=4.5.0",
        ],
        "web": [
            "requests>=2.31.0",
            "fastapi>=0.100.0",
            "pydantic>=2.0.0",
            "uvicorn>=0.23.0",
            "openapi-spec-validator>=0.6.0",
        ],
        "ml": [
            "tensorflow>=2.13.0",
            "pytorch-lightning>=2.0.0",
            "scikit-learn>=1.3.0",
            "mlflow>=2.0.0",
        ],
        "containers": [
            "docker>=6.0.0",
            "kubernetes>=26.0.0",
        ],
        "cicd": [
            "PyGithub>=1.59.0",
            "python-gitlab>=3.0.0",
            "python-jenkins>=1.8.0",
            "pyyaml>=6.0.0",
        ],
        "monitoring": [
            "prometheus-client>=0.17.0",
            "opentelemetry-api>=1.20.0",
            "structlog>=23.0.0",
            "sentry-sdk>=1.30.0",
        ],
        "development": [
            "black>=23.0.0",
            "isort>=5.12.0",
            "flake8>=6.0.0",
            "mypy>=1.5.0",
            "tox>=4.0.0",
            "nox>=2023.0.0",
            "sphinx>=7.0.0",
            "py-spy>=0.3.0",
            "memory-profiler>=0.61.0",
        ],
        "all": [
            "dask>=2023.0.0",
            "ray>=2.0.0",
            "joblib>=1.3.0",
            "openai>=1.0.0",
            "anthropic>=0.5.0",
            "transformers>=4.30.0",
            "torch>=2.0.0",
            "chromadb>=0.4.0",
            "faiss-cpu>=1.7.0",
            "pandas>=1.5.0",
            "scikit-learn>=1.3.0",
            "plotly>=5.0.0",
            "numpy>=1.24.0",
            "scipy>=1.11.0",
            "matplotlib>=3.7.0",
            "seaborn>=0.12.0",
            "jupyter>=1.0.0",
            "pluggy>=1.5.0",
            "cryptography>=41.0.0",
            "fastapi>=0.100.0",
            "pydantic>=2.0.0",
            "uvicorn>=0.23.0",
            "sqlalchemy>=2.0.0",
            "psycopg2-binary>=2.9.0",
            "pymongo>=4.0.0",
            "redis>=4.5.0",
            "tensorflow>=2.13.0",
            "pytorch-lightning>=2.0.0",
            "mlflow>=2.0.0",
            "docker>=6.0.0",
            "kubernetes>=26.0.0",
            "PyGithub>=1.59.0",
            "python-gitlab>=3.0.0",
            "python-jenkins>=1.8.0",
            "prometheus-client>=0.17.0",
            "opentelemetry-api>=1.20.0",
            "structlog>=23.0.0",
            "sentry-sdk>=1.30.0",
            "black>=23.0.0",
            "isort>=5.12.0",
            "flake8>=6.0.0",
            "mypy>=1.5.0",
            "tox>=4.0.0",
            "nox>=2023.0.0",
            "sphinx>=7.0.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "vectorrevamp=unified_test_harness.cli:main",
            "vectorrevamp-cli=unified_test_harness.cli:main",
        ],
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "Intended Audience :: System Administrators",
        "Topic :: Software Development :: Testing",
        "Topic :: Software Development :: Quality Assurance",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Framework :: Pytest",
        "Environment :: Console",
        "Environment :: Web Environment",
    ],
    keywords=[
        "testing",
        "test-generation",
        "ai",
        "machine-learning",
        "parallel-processing",
        "enterprise",
        "quality-assurance",
        "ci-cd",
        "pytest",
        "unittest",
        "coverage",
        "vector-database",
        "llm",
        "automation",
    ],
    project_urls={
        "Homepage": "https://github.com/SWORDIntel/VectorReVamp",
        "Documentation": "https://docs.vectorrevamp.com",
        "Repository": "https://github.com/SWORDIntel/VectorReVamp.git",
        "Issues": "https://github.com/SWORDIntel/VectorReVamp/issues",
        "Changelog": "https://github.com/SWORDIntel/VectorReVamp/blob/main/CHANGELOG.md",
    },
)
